### ISSUE TITLE
out dated

### ISSUE THREAD

**Issue by Azid444** [petidecember/AnnoyMe#2]
asyncio, socketio, pyttsx3
are outdated and no longer work does anyone know a fix to this

**Comment by petidecember** [comment]
What exactly do you mean by "outdated"? Do you get some sort of error when running the python client?

I'm wondering because asyncio is a built-in module [since Python 3.4](https://pypi.org/project/asyncio/) so it can't really be outdated.
Pyttsx3 is on the latest version, though it's from July 2020 it works as advertised.
Newer python-socketio versions will require aiohttp installed.

The simplest way to get the python client working is if you run `pip install -r requirements.txt`, preferably in a [virtual env](https://docs.python.org/3/tutorial/venv.html).
I will update the requirements to include a newer version of python-socketio and aiohttp.
